global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: sentinel-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
        labels:
          service: api
  - job_name: sentinel-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:9100"]
        labels:
          service: worker
